### PR TITLE
set NUM_THREADS=128

### LINKED ISSUE #26: Need to use `make NUM_THREADS=64` or some other large number.
.. otherwise the value is determined from the build machine instead and you'll fail to exploit high performance systems.

### PR DESCRIPTION
**Pull request by isuruf**
Fix #26

### CODE REVIEW

**Comment by isuruf** [comment]
Travis-ci passes in my fork, https://travis-ci.org/isuruf/openblas-feedstock/builds/301758238

**Comment by isuruf** [comment]
Travis-ci passed even though the status is showing pending.

File: recipe/build.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ eval export ${LIBRARY_SEARCH_VAR}="${PREFIX}/lib"
 # Build LAPACK.
 # Enable threading. This can be controlled to a certain number by
 # setting OPENBLAS_NUM_THREADS before loading the library.
-make QUIET_MAKE=1 DYNAMIC_ARCH=1 BINARY=${ARCH} NO_LAPACK=0 NO_AFFINITY=1 USE_THREAD=1 CFLAGS="${CF}" FFLAGS="-frecursive"
+make QUIET_MAKE=1 DYNAMIC_ARCH=1 BINARY=${ARCH} NO_LAPACK=0 NO_AFFINITY=1 USE_THREAD=1 NUM_THREADS=128 CFLAGS="${CF}" FFLAGS="-frecursive"
```
Comment (ocefpaf) [inline recipe/build.sh]: Thanks @isuruf!
